export const DECK_LIST_REQUEST = "DECK_LIST_REQUEST";
export const DECK_LIST_SUCCESS = "DECK_LIST_SUCCESS";
export const DECK_LIST_FAIL = "DECK_LIST_FAIL";

export const DECK_DETAILS_REQUEST = "DECK_DETAILS_REQUEST";
export const DECK_DETAILS_SUCCESS = "DECK_DETAILS_SUCCESS";
export const DECK_DETAILS_FAIL = "DECK_DETAILS_FAIL";
