export const EXERCISE_CREATE_REQUEST = "EXERCISE_CREATE_REQUEST";
export const EXERCISE_CREATE_SUCCESS = "EXERCISE_CREATE_SUCCESS";
export const EXERCISE_CREATE_FAIL = "EXERCISE_CREATE_FAIL";
export const EXERCISE_CREATE_RESET = "EXERCISE_CREATE_RESET";

export const EXERCISE_UPDATE_REQUEST = "EXERCISE_UPDATE_REQUEST";
export const EXERCISE_UPDATE_SUCCESS = "EXERCISE_UPDATE_SUCCESS";
export const EXERCISE_UPDATE_FAIL = "EXERCISE_UPDATE_FAIL";
