export const EXERCISE_CREATE_REQUEST = "EXERCISE_CREATE_REQUEST";
export const EXERCISE_CREATE_SUCCESS = "EXERCISE_CREATE_SUCCESS";
export const EXERCISE_CREATE_FAIL = "EXERCISE_CREATE_FAIL";
export const EXERCISE_CREATE_RESET = "EXERCISE_CREATE_RESET";

export const EXERCISE_UPDATE_REQUEST = "EXERCISE_UPDATE_REQUEST";
export const EXERCISE_UPDATE_SUCCESS = "EXERCISE_UPDATE_SUCCESS";
export const EXERCISE_UPDATE_FAIL = "EXERCISE_UPDATE_FAIL";

export const EXERCISE_LIST_REQUEST = "EXERCISE_LIST_REQUEST";
export const EXERCISE_LIST_SUCCESS = "EXERCISE_LIST_SUCCESS";
export const EXERCISE_LIST_FAIL = "EXERCISE_LIST_FAIL";

export const EXERCISE_DETAILS_REQUEST = "EXERCISE_DETAILS_REQUEST";
export const EXERCISE_DETAILS_SUCCESS = "EXERCISE_DETAILS_SUCCESS";
export const EXERCISE_DETAILS_FAIL = "EXERCISE_DETAILS_FAIL";
