export const WORD_LIST_REQUEST = 'WORD_LIST_REQUEST'
export const WORD_LIST_SUCCESS = 'WORD_LIST_SUCCESS'
export const WORD_LIST_FAIL = 'WORD_LIST_FAIL'

export const WORD_LIST_DECK_REQUEST = 'WORD_LIST_DECK_REQUEST'
export const WORD_LIST_DECK_SUCCESS = 'WORD_LIST_DECK_SUCCESS'
export const WORD_LIST_DECK_FAIL = 'WORD_LIST_DECK_FAIL'

export const WORD_ALL_LIST_REQUEST = 'WORD_ALL_LIST_REQUEST'
export const WORD_ALL_LIST_SUCCESS = 'WORD_ALL_LIST_SUCCESS'
export const WORD_ALL_LIST_FAIL = 'WORD_ALL_LIST_FAIL'

export const WORD_DETAILS_REQUEST = 'WORD_DETAILS_REQUEST'
export const WORD_DETAILS_SUCCESS = 'WORD_DETAILS_SUCCESS'
export const WORD_DETAILS_FAIL = 'WORD_DETAILS_FAIL'
export const WORD_DETAILS_RESET = 'WORD_DETAILS_RESET'

export const WORD_CREATE_REQUEST = 'WORD_CREATE_REQUEST'
export const WORD_CREATE_SUCCESS = 'WORD_CREATE_SUCCESS'
export const WORD_CREATE_FAIL = 'WORD_CREATE_FAIL'
export const WORD_CREATE_RESET = 'WORD_CREATE_RESET'

export const WORD_DRAW_REQUEST = 'WORD_DRAW_REQUEST'
export const WORD_DRAW_SUCCESS = 'WORD_DRAW_SUCCESS'
export const WORD_DRAW_FAIL = 'WORD_DRAW_FAIL'

export const WORD_ADD_EXERCISE_REQUEST = 'WORD_ADD_EXERCISE_REQUEST'
export const WORD_ADD_EXERCISE_SUCCESS = 'WORD_ADD_EXERCISE_SUCCESS'
export const WORD_ADD_EXERCISE_FAIL = 'WORD_ADD_EXERCISE_FAIL'

export const WORD_ADD_CORRECT_ANSWER_REQUEST = 'WORD_ADD_CORRECT_ANSWER_REQUEST'
export const WORD_ADD_CORRECT_ANSWER_SUCCESS = 'WORD_ADD_CORRECT_ANSWER_SUCCESS'
export const WORD_ADD_CORRECT_ANSWER_FAIL = 'WORD_ADD_CORRECT_ANSWER_FAIL'

export const WORD_ADD_WRONG_ANSWER_REQUEST = 'WORD_ADD_WRONG_ANSWER_REQUEST'
export const WORD_ADD_WRONG_ANSWER_SUCCESS = 'WORD_ADD_WRONG_ANSWER_SUCCESS'
export const WORD_ADD_WRONG_ANSWER_FAIL = 'WORD_ADD_WRONG_ANSWER_FAIL'

export const WORD_DELETE_REQUEST = 'WORD_DELETE_REQUEST'
export const WORD_DELETE_SUCCESS = 'WORD_DELETE_SUCCESS'
export const WORD_DELETE_FAIL = 'WORD_DELETE_FAIL'

export const WORD_UPDATE_REQUEST = 'WORD_UPDATE_REQUEST'
export const WORD_UPDATE_SUCCESS = 'WORD_UPDATE_SUCCESS'
export const WORD_UPDATE_FAIL = 'WORD_UPDATE_FAIL'
export const WORD_UPDATE_RESET = 'WORD_UPDATE_RESET'
