export const WORD_LIST_REQUEST = "WORD_LIST_REQUEST";
export const WORD_LIST_SUCCESS = "WORD_LIST_SUCCESS";
export const WORD_LIST_FAIL = "WORD_LIST_FAIL";

export const WORD_DETAILS_REQUEST = "WORD_DETAILS_REQUEST";
export const WORD_DETAILS_SUCCESS = "WORD_DETAILS_SUCCESS";
export const WORD_DETAILS_FAIL = "WORD_DETAILS_FAIL";
