export const WORD_LIST_REQUEST = "WORD_LIST_REQUEST";
export const WORD_LIST_SUCCESS = "WORD_LIST_SUCCESS";
export const WORD_LIST_FAIL = "WORD_LIST_FAIL";

export const WORD_DETAILS_REQUEST = "WORD_DETAILS_REQUEST";
export const WORD_DETAILS_SUCCESS = "WORD_DETAILS_SUCCESS";
export const WORD_DETAILS_FAIL = "WORD_DETAILS_FAIL";

export const WORD_CREATE_REQUEST = "WORD_CREATE_REQUEST";
export const WORD_CREATE_SUCCESS = "WORD_CREATE_SUCCESS";
export const WORD_CREATE_FAIL = "WORD_CREATE_FAIL";
export const WORD_CREATE_RESET = "WORD_CREATE_RESET";
